# Generated by Django 5.0.3 on 2024-04-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=100)),
                ('episodes', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=80)),
                ('year', models.CharField(max_length=10)),
                ('season', models.CharField(max_length=80)),
                ('picture', models.CharField(max_length=100)),
                ('thumbnail', models.CharField(max_length=100)),
                ('relatedAnime', models.CharField(max_length=8000)),
                ('tags', models.CharField(max_length=1000)),
            ],
        ),
    ]
