# Generated by Django 5.0.4 on 2024-04-21 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animeList", "0002_alter_anime_season_alter_anime_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAnime",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "watch_status",
                    models.CharField(
                        choices=[
                            ("watching", "Watching"),
                            ("completed", "Completed"),
                            ("on-hold", "On-hold"),
                            ("dropped", "Dropped"),
                            ("plan_to_watch", "Plan to Watch"),
                        ],
                        max_length=50,
                    ),
                ),
                ("eps_seen", models.IntegerField(default=0)),
                (
                    "score",
                    models.IntegerField(
                        choices=[
                            (1, "(1) Appalling"),
                            (2, "(2) Horrible"),
                            (3, "(3) Very Bad"),
                            (4, "(4) Bad"),
                            (5, "(5) Average"),
                            (6, "(6) Fine"),
                            (7, "(7) Good"),
                            (8, "(8) Very Good"),
                            (9, "(9) Great"),
                            (10, "(10) Masterpiece"),
                        ],
                        max_length=50,
                    ),
                ),
                ("anime", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="animeList.anime")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
