# Generated by Django 5.0.4 on 2024-04-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userManagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
